# Generated by Django 3.1.12 on 2025-02-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250209_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.useraccount'),
        ),
    ]
