# Generated by Django 3.1.12 on 2025-02-09 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250209_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
